export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SOMETHING_TO_ASYNC = 'SET_SOMETHING_TO_ASYNC';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN= 'REMOVE_TOKEN';
export const SET_LOADING_FLAG = 'SET_LOADING_FLAG';